services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_ROOT_DATABASE=${MONGO_DB}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  journey:
    depends_on:
      - postgres
      - mongodb
    container_name: mayo-journey
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local
  mongo-data:
    driver: local
